### ISSUE TITLE
Drag to refresh

### ISSUE THREAD

**Issue by kruug** [bart-kneepkens/Issues#3]
When responding to issues I sometimes see that one of my “Freedoms” has changed status. When I go to check my nation, however, that status does not update.

I do try to drag the screen down to force a refresh (like most web browsers and Facebook use on iOS) but this does not refresh the page.

**Comment by bart-kneepkens** [comment]
Excellent suggestion, I will implement this

**Comment by bart-kneepkens** [comment]
Implemented in https://github.com/bart-kneepkens/Issues/commit/d6cf1c5fd79946f04615991bd8e84b9ea39ba085, this will be included in the next release. Thank you for your suggestion :)

**Comment by bart-kneepkens** [comment]
FYI @kruug it's live, if you update from the App Store you should have it.
